spring:
    application:
        name: user-service
server:
    port: 8082
eureka:
    client:
        service-url:
            defaultZone: http://127.0.0.1:8080/eureka
        register-with-eureka: true
        fetch-registry: true