spring:
    application:
        name: order-service
    cloud:
        nacos:
            discovery:
                namespace: public
                password: nacos
                server-addr: 192.168.131.131:8848
                username: nacos
